<#
    Builds the PhoneDeck shell APK without Gradle.

    Gradle would add a multi-hundred-megabyte download and a pile of
    configuration to produce what is, in the end, one activity and a handful of
    resources. The Android build tools can do it directly:

        aapt2 compile  ->  aapt2 link  ->  javac  ->  d8  ->  zipalign  ->  apksigner

    The server's auth token is injected as a string resource at build time, so
    the app is paired with this PC from the moment it is installed.

    Usage:   powershell -ExecutionPolicy Bypass -File build_apk.ps1 [-Install]
#>
param(
    [switch]$Install,   # adb install the result when the build succeeds
    [switch]$Launch     # ...and start it
)

$ErrorActionPreference = 'Stop'

# ------------------------------------------------------------------ paths --
$here      = Split-Path -Parent $MyInvocation.MyCommand.Path
$root      = Split-Path -Parent $here
$sdk       = Join-Path $root '.tools\android-sdk'
$buildTools= Join-Path $sdk 'build-tools\34.0.0'
$androidJar= Join-Path $sdk 'platforms\android-34\android.jar'
$jdk       = 'C:\Program Files\Microsoft\jdk-17.0.20.101-hotspot'
$out       = Join-Path $here 'build'
$tokenFile = Join-Path $root '.state\token.txt'

$aapt2     = Join-Path $buildTools 'aapt2.exe'
$d8        = Join-Path $buildTools 'd8.bat'
$zipalign  = Join-Path $buildTools 'zipalign.exe'
$apksigner = Join-Path $buildTools 'apksigner.bat'
$javac     = Join-Path $jdk 'bin\javac.exe'
$jar       = Join-Path $jdk 'bin\jar.exe'
$keytool   = Join-Path $jdk 'bin\keytool.exe'

foreach ($tool in @($aapt2, $d8, $zipalign, $apksigner, $javac, $jar, $androidJar)) {
    if (-not (Test-Path $tool)) { throw "missing build tool: $tool" }
}
if (-not (Test-Path $tokenFile)) {
    throw "no token yet at $tokenFile -- start the server once (python run.py) first"
}

# d8 and apksigner are .bat wrappers that locate the JVM through JAVA_HOME.
# The JDK was installed without touching the machine environment, so point
# them at it for the lifetime of this build only.
$env:JAVA_HOME = $jdk
$env:PATH = (Join-Path $jdk 'bin') + ';' + $env:PATH

function Step($text) { Write-Host "==> $text" -ForegroundColor Cyan }

# ------------------------------------------------------- token resource ---
# Written fresh every build so rotating the token is just a rebuild.
$token = (Get-Content $tokenFile -Raw).Trim()
$tokenXml = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by build_apk.ps1. Do not edit; changes are overwritten. -->
<resources>
    <string name="pd_token">$token</string>
</resources>
"@
# Written via .NET rather than Set-Content: PowerShell 5.1's "-Encoding utf8"
# emits a byte-order mark, and aapt2 rejects a BOM before the XML declaration.
$noBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $here 'res\values\token.xml'), $tokenXml, $noBom)

# ---------------------------------------------------------------- clean ---
if (Test-Path $out) { Remove-Item $out -Recurse -Force }
New-Item -ItemType Directory -Force -Path "$out\res", "$out\gen", "$out\classes", "$out\dex" | Out-Null

# ------------------------------------------------------ compile resources -
Step 'aapt2 compile'
& $aapt2 compile --dir (Join-Path $here 'res') -o "$out\res\resources.zip"
if ($LASTEXITCODE -ne 0) { throw "aapt2 compile failed" }

Step 'aapt2 link'
& $aapt2 link `
    -o "$out\app-unaligned.apk" `
    -I $androidJar `
    --manifest (Join-Path $here 'AndroidManifest.xml') `
    --java "$out\gen" `
    --min-sdk-version 28 `
    --target-sdk-version 34 `
    --auto-add-overlay `
    "$out\res\resources.zip"
if ($LASTEXITCODE -ne 0) { throw "aapt2 link failed" }

# ------------------------------------------------------------- compile ----
Step 'javac'
$sources = @()
$sources += (Get-ChildItem "$out\gen" -Recurse -Filter *.java).FullName
$sources += (Get-ChildItem (Join-Path $here 'java') -Recurse -Filter *.java).FullName
# -source/-target 11 keeps the class files well inside what d8 accepts.
# Compiling against android.jar (not the JDK's own API) is why --release is
# not used here; the resulting bootclasspath warning is expected.
#
# javac writes its notes and warnings to stderr even on success. Do NOT pipe
# that through 2>&1: PowerShell 5.1 wraps native stderr in an ErrorRecord,
# which $ErrorActionPreference='Stop' then turns into a failed build. The exit
# code is the only thing worth trusting here.
& $javac -nowarn -source 11 -target 11 -classpath $androidJar -d "$out\classes" $sources
if ($LASTEXITCODE -ne 0) { throw "javac failed" }

Step 'd8 (dex)'
$classFiles = (Get-ChildItem "$out\classes" -Recurse -Filter *.class).FullName
& $d8 --output "$out\dex" --lib $androidJar --min-api 28 $classFiles
if ($LASTEXITCODE -ne 0) { throw "d8 failed" }

# --------------------------------------------------- assemble + sign ------
Step 'packaging classes.dex'
Push-Location "$out\dex"
& $jar uf "$out\app-unaligned.apk" classes.dex
$jarExit = $LASTEXITCODE
Pop-Location
if ($jarExit -ne 0) { throw "adding classes.dex failed" }

Step 'zipalign'
& $zipalign -f -p 4 "$out\app-unaligned.apk" "$out\app-unsigned.apk"
if ($LASTEXITCODE -ne 0) { throw "zipalign failed" }

# A local self-signed key. Fine for sideloading; it is not a Play Store key,
# and reinstalling over a differently-signed copy requires an uninstall first.
$keystore = Join-Path $here 'phonedeck.keystore'
if (-not (Test-Path $keystore)) {
    Step 'creating signing key'
    & $keytool -genkeypair -v -keystore $keystore -storepass phonedeck `
        -keypass phonedeck -alias phonedeck -keyalg RSA -keysize 2048 `
        -validity 10000 -dname "CN=PhoneDeck, OU=Local, O=PhoneDeck, C=IN" | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "keytool failed" }
}

Step 'apksigner'
$apk = Join-Path $out 'phonedeck.apk'
& $apksigner sign --ks $keystore --ks-pass pass:phonedeck --key-pass pass:phonedeck `
    --min-sdk-version 28 --out $apk "$out\app-unsigned.apk"
if ($LASTEXITCODE -ne 0) { throw "apksigner failed" }

& $apksigner verify --min-sdk-version 28 $apk
if ($LASTEXITCODE -ne 0) { throw "signature verification failed" }

$size = [math]::Round((Get-Item $apk).Length / 1KB, 1)
Write-Host ""
Write-Host "BUILT  $apk  ($size KB)" -ForegroundColor Green

# ---------------------------------------------------------------- deploy --
if ($Install) {
    Step 'adb install'
    & adb install -r $apk
    if ($LASTEXITCODE -ne 0) {
        Write-Host "install failed -- if the app was signed with a different key, run:" -ForegroundColor Yellow
        Write-Host "    adb uninstall com.phonedeck.shell" -ForegroundColor Yellow
        throw "adb install failed"
    }
}
if ($Launch) {
    Step 'launching on device'
    & adb shell am start -n com.phonedeck.shell/.MainActivity
}
